### ISSUE TITLE
Please support in-line documentation in indented block

### ISSUE THREAD

**Issue by hanke** [sphinx-gallery/sphinx-gallery#43] opened 2015-07-14 17:13 UTC
Like shown here: http://www.pymvpa.org/examples/searchlight.html

**Comment by lesteve** [comment] 2015-07-14 21:08
This is a duplicate of #33 and the PR #36 is implementing it I believe.

**Comment by lesteve** [comment] 2015-07-14 21:09
Ah sorry I missed the "indented" part of the title, not sure what #36 does about that.

**Comment by agramfort** [comment] 2015-07-15 07:15
I don't think this can work as blocks are executed sequentially.

**Comment by GaelVaroquaux** [comment] 2015-07-15 07:27
> I don't think this can work as blocks are executed sequentially.

Yes, we discussed this with Michael yesterday, and I pretty much said
that we would give up on it.

**Comment by GaelVaroquaux** [comment] 2015-07-15 07:27
Closing the issue, to avoid noise in the tracker.

**Closed by GaelVaroquaux** 2015-07-15 07:27 UTC
