### ISSUE TITLE
sphinx-gallery/0.7.0: TypeError: 'str' object is not callable when building its documentation

### ISSUE THREAD

**Issue by sandrotosi** [sphinx-gallery/sphinx-gallery#727] opened 2020-07-19 19:03 UTC
Hello,
i'm updating the sphinx-gallery package in Debian, and while building its documentation, it fails with this error:

```
generating gallery for auto_examples... [ 90%] plot_7_sys_argv.py
generating gallery for auto_examples... [100%] plot_8_animations.py
MovieWriter ffmpeg unavailable; trying to use pillow instead.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 328, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_gallery.py", line 363, in generate_gallery_rst
    this_fhindex, this_costs = generate_dir_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 363, in generate_dir_rst
    intro, title, cost = generate_file_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 795, in generate_file_rst
    output_blocks, time_elapsed = execute_script(script_blocks,
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 716, in execute_script
    output_blocks.append(execute_code_block(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 602, in execute_code_block
    images_rst = save_figures(block, script_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 317, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 127, in matplotlib_scraper
    image_rsts.append(_anim_rst(anim, image_path, gallery_conf))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 178, in _anim_rst
    anim.save(image_path, writer=writer, dpi=use_dpi)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1109, in save
    writer = alt_writer(
TypeError: 'str' object is not callable

Exception occurred:
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1109, in save
    writer = alt_writer(
TypeError: 'str' object is not callable
The full traceback has been saved in /tmp/sphinx-err-b6h2ajj4.log, if you want to report the issue to the developers.
```

```
# cat /tmp/sphinx-err-b6h2ajj4.log
# Sphinx version: 2.4.3
# Python version: 3.8.4 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 328, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_gallery.py", line 363, in generate_gallery_rst
    this_fhindex, this_costs = generate_dir_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 363, in generate_dir_rst
    intro, title, cost = generate_file_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 795, in generate_file_rst
    output_blocks, time_elapsed = execute_script(script_blocks,
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 716, in execute_script
    output_blocks.append(execute_code_block(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 602, in execute_code_block
    images_rst = save_figures(block, script_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 317, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 127, in matplotlib_scraper
    image_rsts.append(_anim_rst(anim, image_path, gallery_conf))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 178, in _anim_rst
    anim.save(image_path, writer=writer, dpi=use_dpi)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1109, in save
    writer = alt_writer(
TypeError: 'str' object is not callable
```

following up on `MovieWriter ffmpeg unavailable; trying to use pillow instead.` i've installed

```
# ffmpeg -version
ffmpeg version 4.3-3+b1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9 (Debian 9.3.0-14)
configuration: --prefix=/usr --extra-version=3+b1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
```

but now i get this error:

```
generating gallery for auto_examples... [ 90%] plot_7_sys_argv.py
generating gallery for auto_examples... [100%] plot_8_animations.py
MovieWriter stderr:
[gif @ 0x5590f038ea00] GIF muxer supports only a single video GIF stream.
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 -- 


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 230, in saving
    yield self
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1152, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 384, in grab_frame
    self.fig.savefig(self._frame_sink(), format=self.frame_format,
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2119, in print_figure
    result = print_method(
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 450, in print_raw
    fh.write(renderer.buffer_rgba())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 328, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_gallery.py", line 363, in generate_gallery_rst
    this_fhindex, this_costs = generate_dir_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 363, in generate_dir_rst
    intro, title, cost = generate_file_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 795, in generate_file_rst
    output_blocks, time_elapsed = execute_script(script_blocks,
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 716, in execute_script
    output_blocks.append(execute_code_block(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 602, in execute_code_block
    images_rst = save_figures(block, script_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 317, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 127, in matplotlib_scraper
    image_rsts.append(_anim_rst(anim, image_path, gallery_conf))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 178, in _anim_rst
    anim.save(image_path, writer=writer, dpi=use_dpi)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1152, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 368, in finish
    self.cleanup()
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 411, in cleanup
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '370x278', '-pix_fmt', 'rgba', '-r', '10.0', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', '/build/sphinx-gallery-0.7.0/doc/auto_examples/images/sphx_glr_plot_8_animations_001.gif']' returned non-zero exit status 1.

Exception occurred:
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 411, in cleanup
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '370x278', '-pix_fmt', 'rgba', '-r', '10.0', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', '/build/sphinx-gallery-0.7.0/doc/auto_examples/images/sphx_glr_plot_8_animations_001.gif']' returned non-zero exit status 1.
The full traceback has been saved in /tmp/sphinx-err-pqzh4dk3.log, if you want to report the issue to the developers.
```

```
# cat /tmp/sphinx-err-pqzh4dk3.log
# Sphinx version: 2.4.3
# Python version: 3.8.4 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 230, in saving
    yield self
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1152, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 384, in grab_frame
    self.fig.savefig(self._frame_sink(), format=self.frame_format,
  File "/usr/lib/python3/dist-packages/matplotlib/figure.py", line 2203, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line 2119, in print_figure
    result = print_method(
  File "/usr/lib/python3/dist-packages/matplotlib/backends/backend_agg.py", line 450, in print_raw
    fh.write(renderer.buffer_rgba())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 328, in _init_builder
    self.events.emit('builder-inited')
  File "/usr/lib/python3/dist-packages/sphinx/events.py", line 99, in emit
    results.append(callback(self.app, *args))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_gallery.py", line 363, in generate_gallery_rst
    this_fhindex, this_costs = generate_dir_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 363, in generate_dir_rst
    intro, title, cost = generate_file_rst(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 795, in generate_file_rst
    output_blocks, time_elapsed = execute_script(script_blocks,
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 716, in execute_script
    output_blocks.append(execute_code_block(
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/gen_rst.py", line 602, in execute_code_block
    images_rst = save_figures(block, script_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 317, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 127, in matplotlib_scraper
    image_rsts.append(_anim_rst(anim, image_path, gallery_conf))
  File "/build/sphinx-gallery-0.7.0/.pybuild/cpython3_3.8_sphinx-gallery/build/sphinx_gallery/scrapers.py", line 178, in _anim_rst
    anim.save(image_path, writer=writer, dpi=use_dpi)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 1152, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 368, in finish
    self.cleanup()
  File "/usr/lib/python3/dist-packages/matplotlib/animation.py", line 411, in cleanup
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['ffmpeg', '-f', 'rawvideo', '-vcodec', 'rawvideo', '-s', '370x278', '-pix_fmt', 'rgba', '-r', '10.0', '-loglevel', 'error', '-i', 'pipe:', '-vcodec', 'h264', '-pix_fmt', 'yuv420p', '-y', '/build/sphinx-gallery-0.7.0/doc/auto_examples/images/sphx_glr_plot_8_animations_001.gif']' returned non-zero exit status 1.
```

do you know what's causing this issue?

**Comment by sandrotosi** [comment] 2020-07-19 19:09
in case it's useful, matplotlib is installed at version 3.2.2

**Comment by lucyleeow** [comment] 2020-07-19 19:41
I think this is caused by a matplotlib bug that has now been fixed: https://github.com/matplotlib/matplotlib/issues/16965

Could you try updating and see if it fixes the problem?

**Comment by sandrotosi** [comment] 2020-07-19 19:48
the problem is that to upgrade to the latest mpl release (3.3.0) they [require](https://github.com/matplotlib/matplotlib/blob/master/requirements/doc/doc-requirements.txt#L16) sphinx-gallery >= 0.7 which is what i'm trying to upgrade here :)

**Comment by sandrotosi** [comment] 2020-07-19 23:42
for now i worked around this removing `examples/plot_8_animations.py` while building the doc and ignoring `sphinx_gallery/tests/test_full.py` while running tests: they both trigger the same mpl bug; once 0.7.0 reached the debian archive i'll rebuilding matplotlib, and once that reached our archive, i'll try to re-enable those 2 and see how that goes

**Comment by larsoner** [comment] 2020-07-20 19:48
Another option would be to add a little custom [PNGScraper](https://sphinx-gallery.github.io/stable/advanced.html#example-2-detecting-image-files-on-disk) to your build, and actually do a `savefig` directly in the example. Seems a bit cleaner to me than messing with `_static` or anything else. You could even make `PNGScraper` only consider looking for files in specific example filenames if you don't want it to be applied everywhere...

**Comment by larsoner** [comment] 2020-07-20 19:49
Whoops, wrong issue. @sandrotosi your workaround seems reasonable to me

**Comment by larsoner** [comment] 2020-07-20 19:49
Closing since it seems like there are no changes required at our end

**Closed by larsoner** 2020-07-20 19:49 UTC
