### ISSUE TITLE
Orphan boxes in the gallery?

### ISSUE THREAD

**Issue by sciunto** [sphinx-gallery/sphinx-gallery#202] opened 2017-01-30 18:36 UTC
Hi,

In our gallery, we have these orphan boxes after each section: http://scikit-image.org/docs/dev/auto_examples/

What are they for? Can we turn this feature off? Sounds useless for us. I looked into the documentation, and couldn't find a note about that.

Thanks.

**Comment by Titan-C** [comment] 2017-01-30 19:43
> In our gallery, we have these orphan boxes after each section: http://scikit-image.org/docs/dev/auto_examples/

Yes that is a fixed bug and should be fixed in PR #198, is already master and the released version 0.1.8 in PyPI.

> What are they for? Can we turn this feature off? Sounds useless for us. I looked into the documentation, and couldn't find a note about that.

We need the Orphan directive in Sphinx to avoid warnings that the gallery
examples are not inside a toctree. But this has to be used once per
gallery not once per gallery subsection.

But this should be already fixed.

**Comment by sciunto** [comment] 2017-01-30 19:50
OK, thanks. Our update to 0.1.8 is ongoing.

**Comment by lesteve** [comment] 2017-01-31 08:18
Closing, @sciunto feel free to reopen if the issue is not solved.

**Closed by lesteve** 2017-01-31 08:18 UTC
