### ISSUE TITLE
intersphinx links need backreferences_dir

### ISSUE THREAD

**Issue by mdeff** [sphinx-gallery/sphinx-gallery#467] opened 2019-03-28 23:08 UTC
For my intersphinx links (i.e., from examples to API reference) to appear, I had to add
```
    'backreferences_dir': 'gen_modules/backreferences',
    'doc_module': ('pygsp',),  # pygsp is the name of my package
```
to my configuration. Is this a bug or an omission in the doc? The doc only mentions those options for mini-galleries (i.e., links *to* examples).

**Comment by larsoner** [comment] 2019-03-29 01:03
It's entirely possible that this is a bug since most people use the backreferences. Can you see if you can replicate easily with the tests/tinybuild doc build? You can modify the conf then "make html" and "make show" to see.

**Comment by larsoner** [comment] 2019-03-29 01:36
I can confirm that commenting out the `'backreferences_dir'` entry `tinybuild/conf.py` is enough to make `tinybuild/_build/html/auto_examples/plot_numpy_matplotlib.html` no longer properly link to `is_color_like`.

The `doc_module` probably does need to be there either way (and that requirement at least seems reasonable), but we probably do need to document that at least.

So we have one doc problem and one potential bug. I'll have to dig to see how reasonable it is to allow intersphinx without `backreferences` enabled. But at least in the meantime @mdeff can you make your docs work with backreferences enabled, or does that not work for your use case?

**Comment by mdeff** [comment] 2019-03-29 02:07
Thanks for your investigation @larsoner! No problem for me, it works with backreferences enabled.

BTW I find this `doc_module` a bit redundant. I guess people will always want to document their own package, and for the others they could use intersphinx as mentioned in the doc.

**Comment by DanielAdriaansen** [comment] 2019-10-03 20:18
@mdeff thank you for documenting this, I just spent a bunch of time figuring out why my linking to intersphinx documentation wouldn't work in my examples. This was my problem. When setting backreferences_dir it works!

**Comment by lucyleeow** [comment] 2020-04-27 16:19
@larsoner has this been fixed? The link to `is_color_like` in `tinybuild/_build/html/auto_examples/plot_numpy_matplotlib.html`  still works in after commenting out the 'backreferences_dir' in tinybuild/conf.py.

**Comment by larsoner** [comment] 2020-04-27 16:23
@lucyleeow I never intentionally fixed this that I recall. But if you can confirm that works, then I guess we can close.

**Comment by lucyleeow** [comment] 2020-04-27 16:54
Checked in a different build and removing backreferences_dir doesn't prevent interpshinx linking in examples. I'll close for now.

**Closed by lucyleeow** 2020-04-27 16:54 UTC
