### ISSUE TITLE
Idea: make galleries out of the "testing" folder to use each unit test as an example.

### ISSUE THREAD

**Issue by guillaume-chevalier** [sphinx-gallery/sphinx-gallery#875] opened 2021-10-18 21:53 UTC
I'm looking for a way to expose the tests in my documentation. 

Relevant folders of my project: 
- the framework: https://github.com/Neuraxio/Neuraxle/tree/master/neuraxle
- the tests: https://github.com/Neuraxio/Neuraxle/tree/master/testing
- the examples used for galleries: https://github.com/Neuraxio/Neuraxle/tree/master/examples

I feel that it would be interesting to have a way to parse every function starting with "test_" from my test files and treat them as "plot_" files like from the examples. One test file here contains many tests, however.

**Comment by larsoner** [comment] 2021-10-19 15:52
> parse every function starting with "test_" from my test files and treat them as "plot_" files

My sense is that this would require a lot of refactoring of sphinx-gallery, and the use case is pretty specific / far from what sphinx-gallery was designed for (rendering example files like users similar to how users would experience when running them locally).

**Comment by lucyleeow** [comment] 2021-11-12 23:36
I agree with @larsoner that this is a little out of scope. Closing due to this but please let me of any objections.

**Closed by lucyleeow** 2021-11-12 23:36 UTC
