### ISSUE TITLE
How to add custom image to example

### ISSUE THREAD

**Issue by hugadams** [sphinx-gallery/sphinx-gallery#5] opened 2014-12-11 17:19 UTC
Hi,

I love that examples built with "plot_" prefix will autogenerate a plot.  I'm wondering what's the recommended approach to add a custom image to an example that doesn't render a plot.  For example, we have a code that returns HTML tables, or a code that launches an application, and I want to put a screenshot of this at the top of the example in the same place where the plot appears in the examples named "plot_".  Do you have any suggestions?

**Comment by lesteve** [comment] 2015-01-28 20:58
One work-around with the caveat that the gallery won't show any thumbnail for your example: you could just use a image directive in the docstring of your module.

I modified just_code.py like this:

```diff
diff --git a/examples/just_code.py b/examples/just_code.py
index e76c92f..fe5944b 100644
--- a/examples/just_code.py
+++ b/examples/just_code.py
@@ -7,6 +7,9 @@ A short python script
 A script that is not executed when gallery is generated but nevertheless
 gets included as an example.
 Doing a list
+
+.. image:: ../../plot_classifier_comparison_1.png
+
 """
```

and I have plot_classifier_comparison_1.png in `../..` compared to `doc/auto_examples`. It seems to do the trick:

![just_code_with_plot](https://cloud.githubusercontent.com/assets/1680079/5946799/c15463ca-a738-11e4-929b-48a519797878.png)

**Comment by trbedwards** [comment] 2016-11-15 15:48
Is there anyway to get the image directive hack to replace the thumbnail?

**Comment by lesteve** [comment] 2016-11-15 15:55
Yep: http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#using-a-custom-default-thumbnail-image

**Comment by lesteve** [comment] 2016-11-15 15:56
This is not a hack but a feature by the way.

**Comment by trbedwards** [comment] 2016-11-15 16:18
Yes, but this means setting a single default thumbnail for all examples. What I'd like is a different thumbnail for each example, but without having to execute the example (since some examples rely on user input)

**Comment by lesteve** [comment] 2016-11-15 16:37
Not at the moment then. Just curious, what would the purpose of the image and how would it be different from example to example?

**Comment by trbedwards** [comment] 2016-11-15 17:05
There are some example scripts that are either expensive to run or require user input, so it's difficult to automatically produce the plots for those. What I'd like to do is manually run the example myself, get a screenshot or something, then use that for the thumbnail.

**Comment by lesteve** [comment] 2016-11-15 18:04
How long does a single example take ?

We haven't put too much thought about examples where you need user input (I am guessing you mean GUI-like interaction).

Maybe we could think about a way to define a per-example thumbnail if the example is not run. That would not be too complicated although a bit hacky and I am not sure how many people need this.

**Comment by agramfort** [comment] 2016-11-15 18:23
to me using interactivity to build the gallery defeats the purpose of
sphinx-gallery which is
to automate the documentation of packages eg use services like circle ci to
build nightly versions of the web page

**Comment by lesteve** [comment] 2016-11-15 18:27
> to me using interactivity to build the gallery defeats the purpose of sphinx-gallery which is to automate the documentation of packages eg use services like circle ci to build nightly versions of the web page

Yeah I do agree with that too.

**Comment by Titan-C** [comment] 2016-11-15 18:42
> There are some example scripts that are either expensive to run or require user input, so it's difficult to automatically produce the plots for those. What I'd like to do is manually run the example myself, get a screenshot or something, then use that for the thumbnail. 

For examples expensive to run Sphinx-Gallery keeps a record of which
examples have been run and if the source code has not changed they are
not executed again. Sphinx-Gallery also let's you assign which of the
produced plots is going to be used as thumbnail. http://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#choosing-the-thumbnail-image-from-multiple-figures

Now part of the Goal of Sphinx-Gallery is to automate the
documentation build and make sure the examples continue to work with new
versions of your codebase. Thus freezing an example and putting custom
images, is a dangerous option.

For user input use cases we have not considered it, and I really don't
have an idea on how to approach it. But what I will state, is that the
gallery is dedicated for automated build. And If the script needs user
input(GUI, jupyter notebooks, ...), there must be a way to set preset
values and that those values are explicitly shown to the
user(reproducibility matters) and the developers.

**Comment by gregmedlock** [comment] 2018-11-30 18:54
Just raising this again to emphasize a use case--my gallery is a mix of examples that can be reasonably summarized by a plot, and other cases where a conceptual summary figure is more valuable (or, as in the OP, no plot is ever generated).

In my scenario, the summary figure  is unique to each example and is produced with vector art software (e.g. inkscape/illustrator). Using a single default thumbnail across all such examples doesn't make sense here because the examples are completely divergent.

I'm experimenting with workarounds and will post if I come up with something reasonable, but most likely will end up leaving these examples thumbnail-free.

**Comment by choldgraf** [comment] 2018-11-30 21:39
@gregmedlock is your main concern getting a custom thumbnail for each gallery? (aka, it's not enough to just know ahead of time the filename and manually embed with rST)

You may be interested in the image scraper defined here: https://github.com/sphinx-gallery/sphinx-gallery/pull/417

Once that gets merged into s-g-e it might do the trick for you, WDYT? https://github.com/sphinx-gallery/sphinx-gallery-extra/pull/1

**Comment by Titan-C** [comment] 2018-12-05 17:05
Would it be an option for you to load the vector file with
matplotlib. Then Matplotlib will plot it. Then Sphinx-Gallery will
capture that plot and present it in your example HTML file and make a
thumbnail of it.

I understand that such behavior would lead to some unrelated lines of
code to load the figure, but it a quick workaround which you can
surround in comments.

**Comment by larsoner** [comment] 2019-04-03 20:10
This should be addressable via our current scraper API, feel free to open if it's not

**Closed by larsoner** 2019-04-03 20:10 UTC
