### ISSUE TITLE
Generation of unchanged examples 

### ISSUE THREAD

**Issue by NicolasHug** [sphinx-gallery/sphinx-gallery#506] opened 2019-06-19 17:38 UTC
Sorry to come back with this,

it seems that https://github.com/sphinx-gallery/sphinx-gallery/pull/448 worked for sphinx 1.6.5, but updating to sphinx 2.1 will again cause the generation of all examples, not just the ones that were newly updated.

Re-building scikit-learn with sphinx 1.6 takes a few seconds, but with sphinx 2.1 it takes a few minutes.

**Comment by larsoner** [comment] 2019-06-19 17:45
Are you sure that it's *re-running examples* that takes the time? Could it be sphinx *rebuilding the HTML pages* from the unchanged RST? The latter could be caused by https://github.com/numpy/numpydoc/pull/226 if you are on numpydoc 0.9. Either way, you can see if the Sphinx branch https://github.com/sphinx-doc/sphinx/pull/6419 helps diagnose the problem if it is indeed a sphinx rebuilding problem rather than a SG rerunning one.

**Comment by NicolasHug** [comment] 2019-06-19 18:17
Thanks for the quick answer. 

I don't know exactly what the cause is, but in 1.6 I see

```
updating environment: 0 added, 42 changed, 0 removed
```

while in 2.1 I see


```
updating environment: 0 added, 845 changed, 0 removed
```

That happens before sphinx even starts reading the source so I thought this was a SG issue.

It looks like your PR numpy/numpydoc#226 fixes it 

(I get a lot of these warnings though):

```
/home/nico/dev/sphinx/sphinx/ext/autodoc/directive.py:71: RemovedInSphinx40Warning: DocumenterBridge requires a state object on instantiation.
  RemovedInSphinx40Warning)

```

**Comment by larsoner** [comment] 2019-06-19 20:32
> I don't know exactly what the cause is, but in 1.6 I see ...
> while in 2.1 I see ...

If you use my Sphinx branch you should see it tell you explicitly that it's `numpydoc_xref_ignore` changing that breaks things. The breakage you're experiencing motivated both PRs I linked to :)

Can you comment over on numpy/numpydoc#226 that this fixes your problem? Even better if you can do a round of code review so that it can be merged. We mostly just lack review power over on numpydoc which is why it hasn't been merged yet.

**Closed** 2019-06-19 20:32 UTC
