### ISSUE TITLE
Generating gallery sometimes freezes

### ISSUE THREAD

**Issue by thomasjpfan** [sphinx-gallery/sphinx-gallery#479] opened 2019-04-26 13:49 UTC
Generating sphinx gallery sometimes stops generating output: https://circleci.com/gh/scikit-learn/scikit-learn/56204?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by larsoner** [comment] 2019-04-26 13:51
I see this when I run out of memory (sometimes, other times I get "Killed" in the message) or have an example that takes forever. Could one of these be the case for you?

**Comment by GaelVaroquaux** [comment] 2019-04-26 13:55
What makes you think that this is a problem with sphinx-gallery, rather
than with the build that freeze?

**Comment by thomasjpfan** [comment] 2019-04-26 14:43
When the doc build fails, it consistently fails during `generating gallery for ...`, which is where sphinx-gallery is running:

https://github.com/sphinx-gallery/sphinx-gallery/blob/83ea1ac6f5789e3ef50736d6fb8a8c21b4cd8f30/sphinx_gallery/gen_rst.py#L316-L319

It is not always the same example that the build stops at.

**Comment by GaelVaroquaux** [comment] 2019-04-26 14:45
> When the doc build fails, it consistently fails during generating gallery for
> ..., which is where sphinx-gallery is running:

But that's running the example, isn't it? I would think that it's the
corresponding example that is frozen.

**Comment by thomasjpfan** [comment] 2019-04-26 15:11
The build has failed for different examples, so it must be an issue common to all examples. If it is not an issue with sphinx-gallery, it could be a memory issue with plotting. Maybe we need to close figures with `plt.close` at the end of each example?

**Comment by larsoner** [comment] 2019-04-26 15:13
Have you memory profiled (`mprof run`) the examples themselves to make sure they are light weight? On MNE it seems like anything above 1GB is asking for trouble, and 2GB seems practically guaranteed to crash on CircleCI.

**Comment by GaelVaroquaux** [comment] 2019-04-26 15:25
I think that sphinx-gallery does close the figures behind the hood. Or at least it used to. 

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by larsoner** [comment] 2019-06-20 20:45
@thomasjpfan I'm going to close this since  I think it's really a CircleCI issue, but feel free to reopen if this seems incorrect

**Closed by larsoner** 2019-06-20 20:45 UTC

**Comment by J-Christophe** [comment] 2021-03-13 22:17
Hello,

I am facing the same problem (sphinx-gallery==0.8.2). 

To investigate the problem, I added a print DEBUG at this level (file: sphinx_gallery/gen_rst.py):
    iterator = sphinx_compatibility.status_iterator(
        sorted_listdir,
        'generating gallery for %s... ' % build_target_dir,
        length=len(sorted_listdir))
    for fname in iterator:
        print(f "DEBUG {fname}")
        intro, title, cost = generate_file_rst(
            fname, target_dir, src_dir, gallery_conf, seen_backrefs)

The result is the following:
Running Sphinx v3.5.1
making output directory... done
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
DEBUG plot_source_table.pymples_ucb... [ 14%] plot_source_table.py                                                                    
DEBUG plot_source_Mc_DL.pymples_ucb... [ 28%] plot_source_Mc_DL.py                                                                    
DEBUG plot_freq_amp.py
DEBUG plot_source_parameters.py
DEBUG plot_source_joint_sky_pdf.py

The problem comes from the logger.info which stops logging (file: sphinx/util/__init__.py):
    for item in iterable:
        l += 1
        s = "%s[%3d%%] %s" % (
            summary,
            100 * l / length,
            colorize(color, stringify_func(item)),
        )
        if verbosity:
            s += "\n"
        else:
            s = term_width_line(s)
        logger.info(s, nonl=True)

Curiously, the problem is fixed without me understanding why by replacing:
logger.info(s, nonl=True) with logging.getLogger(__name__).info(s, nonl=True)

Regards,
Jean-Christophe

**Comment by larsoner** [comment] 2021-03-14 18:49
Maybe this part is a parallel sphinx build issue?

**Comment by J-Christophe** [comment] 2021-03-15 09:43
This should come from sphinx. I create an issue.

**Comment by J-Christophe** [comment] 2021-03-16 10:12
It was not a bug from sphinx. The solution:
https://github.com/sphinx-doc/sphinx/issues/9005
