### ISSUE TITLE
Having `plot_gallery` as a bool in conf.py raises warning

### ISSUE THREAD

**Issue by tacaswell** [sphinx-gallery/sphinx-gallery#302] opened 2017-10-08 20:30 UTC
Having

```python
plot_gallery = True
```

in `conf.py` results in (seem independent of sphinx version)

```
16:00 $ python make.py html
Running Sphinx v1.5.2
Initializing GitHub plugin

Warning, treated as error:
WARNING: The config value `plot_gallery' has type `bool', defaults to `str'.

Building HTML failed.

```

This fails the build if you have sphinx set to treat warnings as errors.

Replacing with

```python
plot_gallery = 'True'
```

works as expected

**Comment by tacaswell** [comment] 2017-10-08 20:31
This changed from 0.1.12 to 0.1.13

**Comment by Titan-C** [comment] 2017-10-08 20:57
I knew this would fire back at some point. It is not a bug, its a
feature. Please go over the discussion of merged PR #195.

**Comment by tacaswell** [comment] 2017-10-08 21:04
It seemed intentional but I didn't see a mention of it skimming the release note.

Is the prose at https://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#building-without-executing-examples still correct with a bool `False`?

**Comment by Titan-C** [comment] 2017-10-08 21:24
> It seemed intentional but I didn't see a mention of it skimming the release note.

Yes it is an obscure, merged PR and I did miss including all the discussion to it in the release notes.

> Is the prose at https://sphinx-gallery.readthedocs.io/en/latest/advanced_configuration.html#building-without-executing-examples still correct with a bool False?

It should work because the value of  `plot_gallery` passed through `eval` during execution. But it being a bool should give a warning.  The main problem is that this variable can be defined from the command line which only gives string values.  This type mismatch, will always give a warning. @larsoner we should update the docs too, with the same comment as in the default config.

**Comment by larsoner** [comment] 2017-10-09 01:29
https://github.com/sphinx-gallery/sphinx-gallery/pull/304

**Closed** 2017-10-09 09:06 UTC
