### ISSUE TITLE
Wish: option for boilerplate code to execute before a plot

### ISSUE THREAD

**Issue by ivanov** [sphinx-gallery/sphinx-gallery#158] opened 2016-11-03 00:15 UTC
In a discussion of reproducible documentation in matplotlib, the `plot_pre_code` feature of `plot_directive` was used to set the seed of any random number generators that the example plot might produce.

This would be a great feature to add to sphinx-gallery - so that one could specify what code to run before the example (be they custom imports, setting of color cycles, line styles, or random seeds)

**Comment by GaelVaroquaux** [comment] 2016-11-03 06:04
I am +1 if matplotlib wants it, but doesn't it break the notion of
reproducibility? Indeed, if the user does see this code, he/she doesn't
know that he has to run it, and therefore does not reproduce.

**Comment by lesteve** [comment] 2016-11-09 10:33
Looks like matplotlib went of adding explicit seed in their examples (see https://github.com/matplotlib/matplotlib/pull/7386), so let's close this one!

**Closed by lesteve** 2016-11-09 10:33 UTC
